/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ISIS.Code.Class;

import java.awt.Color;
import java.awt.image.BufferedImage;

import javax.swing.JLabel;
import javax.swing.JPanel;

import org.edisoncor.gui.progressBar.ProgressBarRect;
import org.edisoncor.gui.progressBar.ProgressBarRound;
import org.edisoncor.gui.util.Avatar;

import ISIS.Code.Frame.MainFrame;
import ISIS.Code.Panels.MayorSelectionPanel;

/**
 * 
 * @author ISIS
 */
public class Cargando extends JPanel {
	HiloProgreso hilo;

	/**
	 * Creates new form Cargando
	 */
	public Cargando() {
		initComponents();
		iniciarSplash();
		// Creamos un objeto HiloProgreso al cual
		// le pasamos por parámetro la barra de progreso
		
		hilo = new HiloProgreso(jProgressBar1);
		
		// Iniciamos el Hilo
		
		hilo.start();
		
		// Le damos tamaño y posición a nuestro Frame
		
		this.setLocation(200, 200);
		this.setSize(472, 249);
		
		// Liberamos recursos
		hilo = null;
	}

	public void iniciarSplash() {

		this.getjProgressBar1().setBorderPainted(true);
		this.getjProgressBar1().setForeground(new Color(50, 50, 153, 100));
		this.getjProgressBar1().setStringPainted(true);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	
	private void initComponents() {

		jProgressBar1 = new ProgressBarRound();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		panelCurves1 = new PanelCurves();
		panelmayorselected = new MayorSelectionPanel();

		setPreferredSize(new java.awt.Dimension(800, 600));
		setLayout(null);

		add(panelCurves1);
		panelCurves1.setBounds(0, 0, 800, 600);
		add(jProgressBar1);
		jProgressBar1.setBounds(310, 516, 190, 30);
		jProgressBar1.setBackground(Color.CYAN);

		if (MainFrame.mayorSelectionPanel.alcaldeSeleccionado == "Er' Conde")
			jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource(
					"/ISIS/Resource/Backgrounds/LabelConde.png")));
		else if (MainFrame.mayorSelectionPanel.alcaldeSeleccionado == "Manuel Rosales")
			jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource(
					"/ISIS/Resource/Backgrounds/LabelRosales.png"))); // NOI18N
		else if (MainFrame.mayorSelectionPanel.alcaldeSeleccionado == "Jaime Lusinchi")
			jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource(
					"/ISIS/Resource/Backgrounds/LabelLusinchi.png")));
		else if (MainFrame.mayorSelectionPanel.alcaldeSeleccionado == "Chavito")
			jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource(
					"/ISIS/Resource/Backgrounds/LabelChavez.png")));
		add(jLabel1);
		jLabel1.setBounds(0, 0, 800, 600);

		jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/ISIS/Resource/Backgrounds/BackCity2.jpg"))); // NOI18N
		add(jLabel2);
		jLabel2.setBounds(0, 0, 800, 600);

		// pack();
		// </editor-fold>//GEN-END:initComponents
	
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	// public static void main(String args[]) {
	//
	// java.awt.EventQueue.invokeLater(new Runnable() {
	//
	// public void run() {
	//
	// javax.swing.JFrame cargando = new Cargando();
	// cargando.setLocationRelativeTo(null);
	// cargando.setVisible(true);
	//
	//
	//
	// }
	// });
	// }
	
	public javax.swing.JProgressBar getjProgressBar1() {
		return jProgressBar1;
	}

	public void pausa(int mlSeg) {
		try {
			// pausa para el splash
			
			Thread.sleep(mlSeg);
		} catch (Exception e) {
		}
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private ProgressBarRound jProgressBar1;
	private PanelCurves panelCurves1;
	private MayorSelectionPanel panelmayorselected;
	// End of variables declaration//GEN-END:variables
}
