package ISIS.Code.Panels;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

import javax.swing.event.EventListenerList;

import ISIS.Code.Class.PanelCurves;

/**
 * 
 * @author ISIS
 */
public class PanelAtencion extends javax.swing.JPanel {

	/**
	 * Creates new form PanelAtencion
	 */
	public PanelAtencion() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		buttonSeven3 = new org.edisoncor.gui.button.ButtonSeven();
		jLabel1 = new javax.swing.JLabel();
		panelCurves1 = new PanelCurves();
		panelCurves1.start = new Color(0, 0, 255);
		panelCurves1.end = new Color(0, 0, 0);

		setPreferredSize(new java.awt.Dimension(800, 600));
		setLayout(null);
		add(panelCurves1);
		panelCurves1.setBounds(0, 0, 630, 570);
		buttonSeven3.setBackground(new java.awt.Color(0, 0, 255));
		buttonSeven3.setText("Avanzar");
		add(buttonSeven3);
		buttonSeven3.setBounds(655, 530, 116, 35);
		buttonSeven3.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				fireActionEvent(new ActionEvent(this, 0, "NextPanel"));

			}
		});
		jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/ISIS/Resource/Backgrounds/Atencion.png"))); // NOI18N
		add(jLabel1);
		jLabel1.setBounds(0, -20, 800, 600);
	}// </editor-fold>//GEN-END:initComponents

	public void addActionListener(ActionListener listener) {
		eventListenerList.add(ActionListener.class, listener);
	}

	public void removeActionListener(ActionListener listener) {
		eventListenerList.remove(ActionListener.class, listener);
	}

	public ActionListener[] getActionListeners() {
		return eventListenerList.getListeners(ActionListener.class);
	}

	private void fireActionEvent(ActionEvent evt) {
		ActionListener[] actionListeners = getActionListeners();

		for (ActionListener actionListener : actionListeners) {
			actionListener.actionPerformed(evt);
		}
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private org.edisoncor.gui.button.ButtonSeven buttonSeven3;
	private javax.swing.JLabel jLabel1;
	private EventListenerList eventListenerList = new EventListenerList();
	private PanelCurves panelCurves1;
	// End of variables declaration//GEN-END:variables
}
